Admin/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BAG.Models;
namespace Admin.Controllers
{
    public class TicketsController : Controller
    {
        // GET: Tickets
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult RiseTicket()
        {
            return View();
        }
        public string AddTicket(Admin_Tickets newTicket)
        {
            return "";
        }

        public ActionResult TicketDetails()
        {
            return View();
        }
    }
}

Admin/Views/Tickets/Index.cshtml
<div class="right_col" role="main">
    <div class="row">&nbsp;&nbsp;
        <div class="row top_tiles">
            <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                    <div class="icon">
                        <i class="fa fa-user fa-5x"></i>
                    </div>
                    <div class="count">0000</div>
                    <h3>Total Tickets</h3>
                </div>
            </div>
            <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                    <div class="icon">
                        <i class="fa fa-user fa-5x"></i>
                    </div>
                    <div class="count">0000</div>
                    <h3>Open Tickets</h3>
                </div>
            </div>
            <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                    <div class="icon">
                        <i class="fa fa-users fa-5x"></i>
                    </div>
                    <div class="count">0000</div>
                    <h3>Closed Tickets</h3>
                </div>
            </div>
            <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                    <div class="icon">
                        <i class="fa fa-support fa-5x"></i>
                    </div>
                    <div class="count">0000</div>
                    <h3>Emergency Tickets</h3>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading panelpading1" id="panelbackcolor">
                <form class="form" role="search">
                    <span style="position:relative;top:8px;">&nbsp;<i class="fa fa-ticket"></i>&nbsp;Tickets Details</span>
                    <div class="input-group add-on pull-right" style="position:relative;top:8px;">
                        <a href='@Url.Action("RiseTicket", "Tickets")' type="button" class="btn btn-default btn-sm"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp; New Ticket</a>
                    </div>
                </form>
            </div>
            <div class="panel-body">
                <div class="row">
                    <table class="tab-score" data-toggle="table" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1" data-pagination="true" data-sort-name="name" data-sort-order="desc">
                        <thead class="thd">
                            <tr>
                                <th class="headeralign" data-sortable="true">Ticket Id</th>
                                <th class="headeralign" data-sortable="true">Last Update</th>
                                <th class="headeralign" data-sortable="true">Last Replier</th>
                                <th class="headeralign" data-sortable="true">Priority</th>
                                <th class="headeralign" data-sortable="true">Status</th>
                                <th class="headeralign" data-sortable="true">View More</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td align="center">1111</td>
                                <td align="center">21 April 2016 05:21 AM</td>
                                <td align="center">Billing Department</td>
                                <td align="center">Normal</td>
                                <td align="center">Open</td>
                                <th align="center"><a class="btn btn-default" href='@Url.Action("TicketDetails","Tickets")'>View More</a></th>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div>
                </div>
            </div>
        </div>
    </div>
</div>

Admin/Views/Tickets/RiseTicket.cshtml
@model BAG.Models.Admin_Tickets
@{
    ViewBag.Title = "RiseTicket";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="right_col" role="main">
    <div class="row">&nbsp;&nbsp;
        <div class="panel panel-default">
            <div class="panel-heading panelpading2" id="panelbackcolor">
                <form class="navbar-form" role="search">
                    <div class="input-group add-on  ">
                        <i class="fa fa-ticket" aria-hidden="true"></i> Submit a Ticket
                    </div>
                </form>
            </div>
            <div class="panel-body">
                @using (Html.BeginForm("AddTicket", "Tickets", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return AddTicketSuccess  ()" }))
                {
                    <div class="col-md-6">
                        <div class="register-form">
                            <div class="email col-md-10">
                                <label>Your ticket id:</label>
                                <input type="text" class="form-control " name="ticketId" id = "ticketId" placeholder="Not Yet Generated" readonly>
                            </div>
                            <div class="email col-md-10">
                                <label>Ticket Priority:</label>
                                @Html.DropDownListFor(m => m.Ticket_Priority, new SelectList(
                                                new List<Object>{new { value = 0 , text = "Select Priority"  },
                                                                 new { value = 1 , text = "Normal" },
                                                                 new { value = 2 , text = "Medium" },
                                                                 new { value = 3 , text = "High" },
                                                                 new { value = 4 , text = "Emergency" }}, "value", "text", 0), new { @class = "select2_single form-control", @tabindex = "-1", @autofocus = "autofocus" })
                            </div>
                            <div class="email col-md-10">
                                <label>Name:</label>
                                @Html.TextBoxFor(m => m.ContactPerson_name, new { @class = "form-control", @placeholder = "Enter your name" })
                            </div>
                            <div class="email col-md-10">
                                <label>Email:</label>
                                @Html.TextBoxFor(m => m.ContactEmaiId, new { @class = "form-control", @placeholder = "Enter your Email Id" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="register-form">
                            <div class="email col-md-10">
                                <label>Mobile Number</label>
                                @Html.TextBoxFor(m => m.ContactMobileNumber, new { @class = "form-control", @placeholder = "Enter your 10 Digit Mobile number" })
                            </div>
                            <div class="email col-md-10">
                                <label>Issue Description</label>
                                @Html.TextAreaFor(m => m.Issue_Description, new {@class= "form-control", @rows="4", @placeholder = "Enter the short description of an issue" })
                            </div>
                            <div class="email col-md-10">
                                <label>Image Upload:</label>
                                @Html.TextBoxFor(m => m.Issue_PicutureUrl, new { type = "file" })
                                <div id="dvPreview"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12 text-center" id="register-submit">
                        <br />
                        <label id="errMsg" class="warning"></label>
                        <br/>
                        <input  type="submit" value="Submit", class="btn btn-primary btn-md" onclick="return TicketValidationForm()" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href='@Url.Action("Index", "Tickets")' type="button" class="btn btn-default buttoncolor">Cancel</a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<script>
    function TicketValidationForm() {
        var VTicket_Priority = document.getElementById("Ticket_Priority");
        var VContactPerson_name = document.getElementById("ContactPerson_name");
        var VContactEmaiId = document.getElementById("ContactEmaiId");
        var ContactMobileNumber = document.getElementById("ContactMobileNumber");
        var Issue_Description = document.getElementById("Issue_Description");
        var VerrMsg = document.getElementById("errMsg");

        if (VTicket_Priority.value == 0) {
            VerrMsg.innerHTML = "Select Priority Of Ticket";
            VTicket_Priority.focus();
            return false;
        }
        else if (VContactPerson_name.value.trim() == "") {
            VerrMsg.innerHTML = "Enter the Contact Persion Name";
            VContactPerson_name.focus();
            return false;
        }
        else if (!isNaN(VContactPerson_name.value.trim() - 0)) {
            VerrMsg.innerHTML = "Number is not allowed as a Contact Persion Name";
            VContactPerson_name.focus();
            return false;
        }
        else if (VContactEmaiId.value.trim() == "") {
            VerrMsg.innerHTML = "Enter the Valid Email Id";
            VContactEmaiId.focus();
            return false;
        }
        else if (ContactMobileNumber.value.trim() == "" || isNaN(ContactMobileNumber.value.trim() - 0) || ContactMobileNumber.value.trim().length != 10) {
            VerrMsg.innerHTML = "Enter Valid 10 Digit Mobile number";
            ContactMobileNumber.focus();
            return false;
        }
        else if (Issue_Description.value.trim() == "") {
            VerrMsg.innerHTML = "Short description of an issue can't be an empty.";
            Issue_Description.focus();
            return false;
        }
        else {
            VerrMsg.innerHTML = "";
            return true;
        }
    }
</script>

Admin/Views/Tickets/TicketDetails.cshtml
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<div class="right_col" role="main">
    <div class="row">
        <br />
        <br />
        <br />

        <div class="panel panel-default ">
            <div class="panel-heading" id="panelbackcolor">
                <p>Issue Description</p>
            </div>
            <div class="container">
                <br />
                <div class="col-md-8 col-md-offset-2">
                    <form class="form" role="search">


                        <div class="add-on  ">

                            <article class="media event">
                                <a class="pull-left date">
                                    <p class="month">April</p>
                                    <p class="day">23</p>
                                </a>
                                <div class="media-body">
                                    <a class="title" href="#" style="font-size:15pt;">Registrtion Issue</a>
                                    <p>Posted by Madan S B on 23 April 2016 09:01 AM</p>
                                </div>
                            </article>


                        </div>
                        <div class="add-on pull-right  ">

                            <img src="/images/img.jpg" class="img-responsive hidden-xs" style="height:60px;width:60px;position:relative;top:-55px;">


                        </div>
                    </form>
                    <div>
                        <p>
                            Respected Customers,
                        </p>
                        <p>

                            We would like to inform you that as we are improving our web services
                            so no tickets are pending and still we are improvising our services
                            with our web servers and we request you to kindly share your issues so
                            that our team will resolve asap and we will reach to our customer
                            satisfaction and also call us for any issues and raise tickets so that
                            we can improvise our service well.
                        </p>


                        <p>
                            This is humble request for all customer if they face any issue with
                            their services please feel free to share your views on tickets. So
                            that we can improvise our web server services well and give better
                            service to our client.
                        </p>

                    </div>
                    <div>
                        <h4 id="show">Leave Reply</h4>

                    </div>
                    <div>
                        <div class="email col-md-6" id="commentbox" style="display:none;">
                            <label for="Campian Name">Email:</label><div class="clear"></div>
                            <input type="text" class="form-control " name="Campian Name">

                            <label for="email">Response:</label><div class="clear"></div>
                            <textarea class="form-control" rows="3" id="comment"></textarea>
                        </div>

                        <div class="col-md-12" id="commentbox1" style="display:none;">
                            <br />
                            <button type="submit" class="btn btn-primary btn-md">Send</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <button class="btn btn-default buttoncolor " data-backdrop="static" data-keyboard="false">Cancel</button>

                        </div>

                    </div>
                </div>

            </div>

        </div>

    </div>

</div>
<script>
  $(document).ready(function () {

        $("#show").click(function () {
            $("#commentbox").show();
            $("#commentbox1").show();
        });
  });
</script>