Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BAG.Models;
using BAG.BusinessLogic;


namespace Admin.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

       
        public ActionResult LoginProcess(Admin_Login u)
        {
            try
            {
                AccountsBLL obj = new AccountsBLL();
                U_USR_Lgn obj1 = new U_USR_Lgn();
                obj1.Email_ID = u.EmailId;
                obj1.Pwd = u.Password;
                obj1.Created_by = u.UserName;
                U_ADMIN_lOGIN_Ref status = obj.LoginPro(obj1);
                
                if (status != null)
                {
                    Session["AdminId"] = status.UserId;
                    Session["AdminName"] = status.UserName;
                    Session["AdminPic"] = status.ProfilePic;
                    ModelState.Clear();
                    return Content("Success", "text/html");
                }
                else
                {
                    return Content("Invalid User", "text/html");
                }
            }
            catch
            {
              return Content("Invalid Password", "text/html");
            }
        }
        
        [Admin.FilterConfig.SessionAuthorize]
        public ActionResult DashBoard()
        {
            DashboardGroup details = new DashboardGroup();
            DashboardTotals tempTotal = new DashboardTotals();
            MembersBLL memBLL = new MembersBLL();
            EventsBLL eveBLL = new EventsBLL();
            ItemsBLL iteBLL = new ItemsBLL();

            List<DashboardEvents> eves = new List<DashboardEvents>();
            List<DashboardVendors> vends = new List<DashboardVendors>();
            tempTotal.TotalMembers = memBLL.MembersCount();
            tempTotal.TotalEvents = eveBLL.EventsCount();
            tempTotal.TotalItems = iteBLL.ItemsCount();
            tempTotal.TotalVendors = "0000";

            vends.Add(new DashboardVendors("1", "Shop1", "Vendor1", DateTime.Now));
            vends.Add(new DashboardVendors("2", "Shop2", "Vendor2", DateTime.Now));
            vends.Add(new DashboardVendors("3", "Shop3", "Vendor3", DateTime.Now));
            vends.Add(new DashboardVendors("4", "Shop4", "Vendor4", DateTime.Now));
            vends.Add(new DashboardVendors("5", "Shop1", "Vendor5", DateTime.Now));

            details.Totals = tempTotal;
            details.Members = memBLL.Recent5Members();
            details.Events = eveBLL.Recent5Events();
            details.Items = iteBLL.Recent5Items();
            details.Vendors = vends.ToArray();
            return View(details);
        }

        [Admin.FilterConfig.SessionAuthorize]
        public ActionResult Eventdescription()
        {
            return View();
        }

        public ActionResult Events()
        {
            return View();
        }

        public ActionResult Additems()
        {
            return View();
        }

        public ActionResult EditProfile()
        {
            return View();
        }

        public ActionResult Notifications()
        {
            return View();
        }

        public ActionResult paymentstatus()
        {
            return View();
        }

        public ActionResult subadmin()
        {
            return View();
        }

        public ActionResult paymentrevert()
        {
            return View();
        }

        public ActionResult Editsubadmin()
        {
            return View();
        }

        public ActionResult Logout()
        {
            Session.Clear();
            Session.Abandon();
            Session.RemoveAll();
            return RedirectToAction("Index", "Home");
        }
    }
}

Admin/Controllers/NotificationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Admin.Controllers
{
    public class NotificationsController : Controller
    {

        //private AdminGeneralClient pcs = new AdminGeneralClient();
        public ActionResult Index()
        {
            return View();
        }
    }
}

Admin/Controllers/VendorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Admin.Controllers
{
    public class VendorsController : Controller
    {
        // GET: Vendors
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult VendorsProfile()
        {
            return View();
        }
        public ActionResult AddVendors()
        {
            return View();
        }
        public ActionResult Edit()
        {
            return View();
        }
        public ActionResult Category()
        {
            return View();
        }
        public ActionResult EditCategory()
        {
            return View();
        }
        public ActionResult Products()
        {
            return View();
        }
        public ActionResult EditProducts()
        {
            return View();
        }
    }
}

Admin/Views/Home/DashBoard.cshtml
@model BAG.Models.DashboardGroup
<div class="right_col" role="main">
    <br />
    <div class="">
        <div class="row top_tiles">
            <a href='@Url.Action("Index", "Members")'>
                <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="tile-stats">
                        <div class="icon">
                            <i class="fa fa-users"></i>
                        </div>
                        <div class="count">@Model.Totals.TotalMembers</div>
                        <h3>Total Members</h3>
                    </div>
                </div>
            </a>
            <a href='@Url.Action("Index", "Events")'>
                <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="tile-stats">
                        <div class="icon">
                            <i class="fa fa-tasks"></i>
                        </div>
                        <div class="count">@Model.Totals.TotalEvents</div>
                        <h3>Total Events</h3>
                    </div>
                </div>
            </a>
            <a href='@Url.Action("Index", "GiftItems")'>
                <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="tile-stats">
                        <div class="icon">
                            <i class="fa fa-gift"></i>
                        </div>
                        <div class="count">@Model.Totals.TotalItems</div>
                        <h3>Total Gift Items</h3>
                    </div>
                </div>
            </a>
            <a href='@Url.Action("Index", "Vendors")'>
                <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12"> 
                    <div class="tile-stats">
                        <div class="icon">
                            <i class="fa fa-black-tie"></i>
                        </div>
                        <div class="count">@Model.Totals.TotalVendors</div>
                        <h3>Total Vendors</h3>
                    </div>
                </div>
            </a>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Recent 5 Members</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        @foreach (var item in Model.Members)
                        {
                            <a href='@Url.Action("MemberDetails", "Members", new { Id = item.Member_Id})'>
                                <article class="media event">
                                    <div class="pull-left date">
                                        <p class="month">@item.Member_CreatedDate.ToString("MMM")</p>
                                        <p class="day">@item.Member_CreatedDate.ToString("dd")</p>
                                    </div>
                                    <div class="media-body">
                                        <p><strong>@item.Member_Name</strong></p>
                                        <p>@item.Member_EmailId</p>
                                    </div>
                                </article>
                            </a><br>
                        }
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Recent 5 Events</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        @foreach (var item in Model.Events)
                        {
                            <a href='@Url.Action("EventProfile", "Events", new { Id = item.Event_Id})'>
                                <article class="media event">
                                    <div class="pull-left date">
                                        <p class="month">@item.Event_CreateDate.ToString("MMM")</p>
                                        <p class="day">@item.Event_CreateDate.ToString("dd")</p>
                                    </div>
                                    <div class="media-body">
                                        <p><strong>@item.Event_Name</strong></p>
                                        <p>@item.Event_Organizer</p>
                                    </div>
                                </article>
                            </a><br>
                        }
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Recent 5 Vendors</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        @foreach (var item in Model.Vendors)
                        {
                            <a href='@Url.Action("VendorsProfile", "Vendors", new { Id = item.Vendor_Id})'>
                                <article class="media event">
                                    <div class="pull-left date">
                                        <p class="month">@item.Vender_CreateDate.ToString("MMM")</p>
                                        <p class="day">@item.Vender_CreateDate.ToString("dd")</p>
                                    </div>
                                    <div class="media-body">
                                        <p><strong>@item.Vendor_ShopName</strong></p>
                                        <p>@item.Vendor_Name</p>
                                    </div>
                                </article>
                            </a><br>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Admin/Views/Home/EditProfile.cshtml
<div class="right_col" role="main">

    <div class="row">
        &nbsp;&nbsp;
        <div class="panel panel-default">
            <div class="panel-heading" id="panelbackcolor">
                <form class="navbar-form" role="search">
                    <div class="input-group add-on  ">
                        Edit Profile
                    </div>
              
                </form>
            </div>
            <div class="panel-body">

                <form action="" enctype="multipart/form-data" method="post">
                    <div class="col-md-6">
                        <div class="register-form">
                            <div class="email col-md-10">
                                <label for="email">First Name:</label><div class="clear"></div>
                                <input type="text" class="form-control " name="firstname" value="Madan">
                            </div>
                            <div class="email col-md-10">
                                <label for="email">Last Name:</label><div class="clear"></div>
                                <input type="text" class="form-control " name="firstname" value="Madan">
                            </div>

                            <div class="name col-md-10">
                                <label for="name">Gender&nbsp;</label>
                                <div>
                                    <input data-val="true" data-val-number="The field gender must be a number." data-val-required="The gender field is required." id="omemberdetails_gender" name="omemberdetails.gender" type="radio" value="1">
                                    <label for="Male">Male</label>

                                    &nbsp;&nbsp;<input id="omemberdetails_gender" name="omemberdetails.gender" type="radio" value="2">
                                    <label for="Female">Female</label>
                                </div>
                            </div>
                            <div class="email col-md-10">
                                <label for="email">Date Of Birth:</label><div class="clear"></div>
                                <input type="text" class="form-control " name="firstname">
                            </div>
                            <div class="email col-md-10">
                                <label for="email">Address:</label><div class="clear"></div>
                                <input type="text" class="form-control " name="firstname">
                            </div>
                            <div class="email col-md-10">
                                <label for="email">City:</label><div class="clear"></div>
                                <input type="text" class="form-control " name="firstname">
                            </div>
                            <div class="email col-md-10">
                                <label for="email">Country:</label><div class="clear"></div>
                                <input type="text" class="form-control " name="firstname">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="register-form">
                            <div class="email col-md-10">
                                <label for="email ">Profession:</label><div class="clear"></div>
                                <input type="text" class="form-control " name="firstname">
                            </div>
                            <div class="name col-md-10">
                                <label for="name">Is Married?&nbsp;</label>
                                <div>

                                    <input id="Ismarried1" name="omemberdetails.is_married" type="radio" value="1">
                                    <label for="Yes">Yes</label>
                                    &nbsp;&nbsp;<input data-val="true" data-val-number="The field is_married must be a number." data-val-required="The is_married field is required." id="Ismarried2" name="omemberdetails.is_married" type="radio" value="2">
                                    <label for="No">No</label>
                                </div>
                            </div>
                            <div id="avsdate" class="email col-md-10">
                                <label for="Aniversary Date">Aniversary Date:</label><div class="clear"></div>
                                <input type="date" class="form-control " name="Aniversary Date">
                            </div>
                            <div class="email col-md-10">
                                <label for="email">About me:</label><div class="clear"></div>
                                <input type="text" class="form-control " name="firstname">
                            </div>
                            <div class="email col-md-10">
                                <label for="email">Profile Picture:</label><div class="clear"></div>
                                <input id="file" type="file" name="file">
                                <div id="dvPreview"></div>
                            </div>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="col-md-12 text-center" id="register-submit">
                        <button type="submit" class="btn btn-primary btn-md">Update</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <button class="btn btn-default buttoncolor " data-backdrop="static" data-keyboard="false">Cancel</button>

                    </div>



                </form>

            </div>






        </div>
    </div>
    
    </div>

Admin/Views/Home/Index.cshtml
@model BAG.Models.Admin_Login
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LoginPartial.cshtml";
}
@using (Ajax.BeginForm("LoginProcess", "Home", null, new AjaxOptions{ HttpMethod = "POST", UpdateTargetId = "msgId", OnSuccess= "Redirect()"}, new { Id= "loginId"}))
{
    <h1>LOGIN</h1>
    <div>
        @Html.TextBoxFor(m => m.EmailId, new { @class = "form-control", @placeholder = "Username" })
    </div>
    <div>
        @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Password" })
    </div>
    <div>
        <input type="submit" class="btn btn-default submit" value="Login" />
        @Html.ActionLink("Lost your password?", "RestPassword", "Home", null, new { @class = "reset_pass" })
    </div>
    <div class="col-md-12 text-center" id="msgId">

    </div>
    <div class="clearfix"></div>
    <div class="separator">
        <div class="clearfix"></div>
        <br />
        <div>
            <h1><i class="fa fa-paw" style="font-size: 26px;"></i> Brew A Gift!</h1>
            <p>©2016 All Rights Reserved. Privacy and Terms</p>
        </div>
    </div>
}
<script>
    function Redirect() {
        if (document.getElementById("msgId").innerHTML == "Success") {
            document.getElementById("msgId").style.display = "none";
            window.location.href = window.location.origin + '/Home/Dashboard';
        }
    }
</script>

Admin/Views/Home/Notifications.cshtml
@{
    ViewBag.Title = "Notifications";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Notifications</h2>

Admin/Views/Home/paymentrevert.cshtml
 
<div class="right_col" role="main">
    &nbsp;&nbsp;&nbsp;
    <div class="panel panel-default">
        <div class="panel-heading" id="panelbackcolor" style="position: static; padding: 10px 15px; padding-bottom: 0px; ">
            <form class="navbar-form" role="search">
                <div class="input-group add-on  ">
                    Payment Revert
                </div>


            </form>

        </div>
        <div class="panel-body">
            <div class="row">


            </div>
            <div class="row">

                <div class="table-responsive tablealign">
                    <br>
                    <table class="table table-bordered table-hover tablealign" style="background-color:white;">

                        <thead>
                            <tr>
                                <th class="headeralign">Transaction Id</th>
                                <th class="headeralign">Item Id</th>
                                <th class="headeralign">Event Name</th>
                                <th class="headeralign">Wishlist Name</th>
                                <th class="headeralign">Item Name</th>
                                <th class="headeralign">Amount</th>
                                <th class="headeralign">Contributer Name </th>
                                <th class="headeralign">Status</th>
                                <th class="headeralign">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th class="headeralign">1</th>
                                <td align="center">542</td>
                                <td align="center">aaaa</td>
                                <td align="center">Maaaaaa</td>
                                <td align="center">Mobile</td>
                                <td align="center">1000</td>
                                <td align="center">Kiran</td>
                                <td align="center">
                                    <span class="label label-success">Recived</span>
                                </td>
                                <td align="center">

                                    <p data-placement="top" data-toggle="tooltip"><button class="btn btn-default  btn-xs buttoncolor  ">Delete </button></p>

                                </td>


                            </tr>





                        </tbody>

                    </table>
                </div><!--end of .table-responsive-->
            </div>

        </div>
    </div>


</div>